parameters:
    api_access_token: '%env(API_ACCESS_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%product_image_directory%'

    App\EventSubscriber\ApiTokenSubscriber:
        arguments:
            $apiToken: '%env(API_TOKEN)%'

    App\:
        resource: '../src/'
