parameters:
    api_access_token: '%env(API_ACCESS_TOKEN)%'
    telegram_bot_token: '%env(default::TELEGRAM_BOT_TOKEN)%'
    uploads_directory: '%kernel.project_dir%\public\uploads\products\'
    asset_directory: ''
services:
    _defaults:
        autowire: true
        autoconfigure: true

#    App\EventSubscriber\ApiTokenSubscriber:
#        arguments:
#            $apiToken: '%env(API_TOKEN)%'

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php}'

    App\Service\Files\UploadFileService:
        arguments:
            $targetDirectory: '%uploads_directory%'

    App\Service\API\BotService:
        arguments:
            $botToken: '%telegram_bot_token%'




